# Generated by Django 3.2.5 on 2021-07-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=40)),
                ('balance', models.IntegerField(max_length=40)),
                ('datetime', models.DateTimeField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('balance', models.IntegerField(max_length=40)),
            ],
        ),
    ]
