# Generated by Django 3.2.5 on 2021-07-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0002_auto_20210703_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
