# Generated by Django 3.2.5 on 2021-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0003_alter_transaction_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('receivers', models.CharField(max_length=40)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
