# Generated by Django 3.2.5 on 2021-07-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0004_auto_20210704_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsform',
            name='datetime',
        ),
    ]
