# Generated by Django 3.2.5 on 2021-07-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0005_remove_transactionsform_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionsForm',
        ),
    ]
