# Generated by Django 3.2.5 on 2021-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0006_delete_transactionsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('receivers', models.CharField(max_length=40)),
            ],
        ),
    ]
