# Generated by Django 3.2.5 on 2021-07-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0007_transactionsform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsform',
            old_name='receivers',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transactionsform',
            old_name='senders',
            new_name='sender',
        ),
    ]
