# Generated by Django 3.2.5 on 2021-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0009_auto_20210705_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='irene@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Irene', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionsform',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionsform',
            name='receiver',
            field=models.EmailField(default='irene@gmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='transactionsform',
            name='sender',
            field=models.EmailField(default='irene@gmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='irene@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Irene', max_length=30),
        ),
    ]
