# Generated by Django 3.2.5 on 2021-07-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0010_auto_20210705_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ac_bal',
            new_name='acc_bal',
        ),
    ]
