# Generated by Django 3.2.5 on 2021-07-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0011_rename_ac_bal_transaction_acc_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='acc_bal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cr_amt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deb_amt',
        ),
    ]
