# Generated by Django 3.2.5 on 2021-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0012_auto_20210705_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='acc_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cr_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deb_amt',
            field=models.IntegerField(default=0),
        ),
    ]
