# Generated by Django 3.2.5 on 2021-07-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0013_auto_20210705_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
