# Generated by Django 3.2.5 on 2021-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0014_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('deb_amt', models.IntegerField()),
                ('cr_amt', models.IntegerField()),
                ('acc_bal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transactionsform',
            name='receiver',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='transactionsform',
            name='sender',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
