# Generated by Django 3.2.5 on 2021-07-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0015_auto_20210705_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
