# Generated by Django 3.2.5 on 2021-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0019_transactionsform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
