# Generated by Django 3.2.5 on 2021-07-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0020_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionsForm',
        ),
    ]
