# Generated by Django 3.2.5 on 2021-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0021_delete_transactionsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=40)),
                ('amount', models.IntegerField()),
                ('receiver', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
