# Generated by Django 3.2.5 on 2021-07-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Banking_App', '0022_transactionsform_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
